### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by Lina1478** [KirillMaidanyuk/Converter#4]
- [x] Подбор цветовой палитры

**Comment by KirillMaidanyuk** [comment]
- [ ] Работа с типографикой (подбор шрифтов);
- [ ] Подбор и обработка иконок;
- [ ] Создание набора элементов интерфейса
